-- MySQL Script generated by MySQL Workbench
-- Thu Jan 29 20:12:51 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`run_li_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`run_li_shop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `fecha_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(100) NOT NULL,
  `stock_total` INT UNSIGNED NOT NULL,
  `costo_china` DECIMAL(10,2) NOT NULL,
  `fecha_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `stock_minimo` INT UNSIGNED NOT NULL,
  `run_li_shop_id` INT NOT NULL,
  `marcas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modelos_run_li_shop_idx` (`run_li_shop_id` ASC) VISIBLE,
  INDEX `fk_modelos_marcas1_idx` (`marcas_id` ASC) VISIBLE,
  CONSTRAINT `fk_modelos_run_li_shop`
    FOREIGN KEY (`run_li_shop_id`)
    REFERENCES `mydb`.`run_li_shop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modelos_marcas1`
    FOREIGN KEY (`marcas_id`)
    REFERENCES `mydb`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`clientes_tiendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes_tiendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_comercial` VARCHAR(100) NOT NULL,
  `rfc_tax_id` VARCHAR(20) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos_surtido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidos_surtido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `folio_embarque` VARCHAR(45) NOT NULL,
  `estatus` VARCHAR(20) NOT NULL,
  `clientes_tiendas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_surtido_clientes_tiendas1_idx` (`clientes_tiendas_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_surtido_clientes_tiendas1`
    FOREIGN KEY (`clientes_tiendas_id`)
    REFERENCES `mydb`.`clientes_tiendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT UNSIGNED NOT NULL,
  `talla` DECIMAL(3,1) NOT NULL,
  `precio_venta` DECIMAL(10,2) NOT NULL,
  `modelos_id` INT NOT NULL,
  `pedidos_surtido_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_pedido_modelos1_idx` (`modelos_id` ASC) VISIBLE,
  INDEX `fk_detalle_pedido_pedidos_surtido1_idx` (`pedidos_surtido_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_pedido_modelos1`
    FOREIGN KEY (`modelos_id`)
    REFERENCES `mydb`.`modelos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_pedido_pedidos_surtido1`
    FOREIGN KEY (`pedidos_surtido_id`)
    REFERENCES `mydb`.`pedidos_surtido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
